### ISSUE TITLE
Dear @AraiEzzra

### ISSUE THREAD

**Issue by memayddk** [AraiEzzra/DDKCORE#171]
Can u teach me about coding ?..i'm very interested about this ....

**Comment by ayubsulong** [comment]
When can we vote though?

**Comment by memayddk** [comment]
U ask me when we can vote?

**Comment by ayubsulong** [comment]
Nope. I'm asking the management if they can read this ;)

**Comment by Minztaz27** [comment]
Hi how can get domain?it's to hard get from td

**Comment by AraiEzzra** [comment]
Dear all, please refer DDK Official Blog ( https://blog.ddkoin.com ) for latest update. You also can refer any of 100 TD's (Trusted Delegate) from your group/countries for getting more info. Every TD, Sub-TD, Group and each countries will have their own nodes/wallet for making the transaction to connect to "1" DDK Blockchain (Public Ledger).
