### ISSUE TITLE
DDKOIN FINAL LAUNCING

### ISSUE THREAD

**Issue by Ginds** [AraiEzzra/DDKCORE#526]
When we are Stakeholder can be voting, P2P, Stake and Get Reward? Now we are waiting on 10 months since June 2018.

**Comment by AraiEzzra** [comment]
Hello Ginds, 

To know the launch process of CORE DDK and when the launch of the New Core is open to the public, please refer DDK Official Blog at the following link:

https://blog.ddkoin.com/


Thanks

**Comment by Ginds** [comment]
Okay thankyou
