### ISSUE TITLE
When launching?

### ISSUE THREAD

**Issue by Ginds** [AraiEzzra/DDKCORE#565]
When? when? Too many announcement but the final is not.

**Comment by AraiEzzra** [comment]
Dear @Ginds ,

Please get latest info from DDK Official BLOG or DDK Official Facebook page for exact date when we will start open the door for public on DDK Mainnet by this week. 

On top of that, you also could refer to any TD (Trusted Delegate) from this list ( https://ddkoin.com/trusted-delegates ) to get correct info to assist you and guide any token holders.

Regards

**Comment by Ginds** [comment]
is true that Ddkoin lsunching today?
