### ISSUE TITLE
Beta Testing?

### ISSUE THREAD

**Issue by Ginds** [AraiEzzra/DDKCORE#596]
When the date of DDK is listed with simex? 

Please give the date!

**Comment by suppuddk** [comment]
previous launch date was when new core is launch simex will launch

New Date to launch simex is 27th may - 31st may

**Comment by AraiEzzra** [comment]
Dear @Ginds ,

Please read our latest announcement for your questions on exchanger from here :

https://announcements.ddkoin.com/?p=778

Regards
