### ISSUE TITLE
Generator Block

### ISSUE THREAD

**Issue by Ginds** [AraiEzzra/DDKCORE#614]
Why the Generator block do not appear in blockchain?

**Comment by AraiEzzra** [comment]
Dear @Ginds ,

Can you elaborate more regarding your question about "Generator block"?

Thanks

**Comment by Ginds** [comment]
https://explorer.lisk.io/blocks/ like in lisk appear “generated by”

**Comment by AraiEzzra** [comment]
Dear @Ginds ,

In an open source and decentralize application such as DDK, all information on which DELEGATE forging the block for the transaction will be displayed transparently.

Anyone can refer this website to publicly view which Delegate is forging each block transparently : https://mainnetexplorer.ddkoin.com/

TQ
