### ISSUE TITLE
Mainnet Explorer

### ISSUE THREAD

**Issue by Ginds** [AraiEzzra/DDKCORE#615]
The mainnet explorer is still masternode not new core, where is the blockchain explorer that has been a new core

**Comment by Ginds** [comment]
?

**Comment by AraiEzzra** [comment]
Dear @Ginds ,

Right now, we have the Explorer for Pre-Production (New Core) can be refer from this link : http://ddkexplorer.extreme.org.in/websocket/#/dashboard

Developers are working to connect the explorer on the Production Mainnet (New Core) and change to new domain that will be publish here : https://mainnetexplorer.ddkoin.com ) .

DDK Team will make an announcement on here when it's ready : https://announcements.ddkoin.com/

TQ

**Comment by Ginds** [comment]
But i can’t open this link: http://ddkexplorer.extreme.org.in/websocket/#/dashboard

**Comment by AraiEzzra** [comment]
Dear @Ginds ,

Please wait when the REAL mainnet explorer ready on here : https://mainnetexplorer.ddkoin.com/

For http://ddkexplorer.extreme.org.in/websocket/#/dashboard its just for BETA TEST for our developers work.

TQ
