### ISSUE TITLE
2nd pp

### ISSUE THREAD

**Issue by EdyFromBogor** [AraiEzzra/DDKCORE#621]
Is it possible to rollback the 2nd passphrase of my DDK account that was taken illegally by someone

**Comment by AraiEzzra** [comment]
Dear @EdyFromBogor ,

It's not possible to rollback for certain accounts only on blockchain application. It will affect other users' transactions as well.

Please read our announcement to aware we're on which phase now from here : https://announcements.ddkoin.com/?p=778

Thanks
