### ISSUE TITLE
Airdrop and Referral Tree?

### ISSUE THREAD

**Issue by Ginds** [AraiEzzra/DDKCORE#642]
Where is the Airdrop and Refferal Tree?

**Comment by AraiEzzra** [comment]
Dear @Ginds ,

Right now our developer are working on this matter. Please follow up the task and codes from this link to monitor developer's task and work :

Github Pull Request : 
1) https://github.com/AraiEzzra/DDKCORE/pull/612 

Trello Done : 
1) https://trello.com/c/iLi4SU29/53-declare-airdrop
2) https://trello.com/c/7LenTuog/71-create-airdrop-statistics-front

Trello Not done (WIP) : 
1) https://trello.com/c/oE9Xqxwh/23-development-airdrop-statistic-page
2) https://trello.com/c/8sBJuDZC/276-airdrop-statistics

TQ
