### ISSUE TITLE
Issue at CREATE_TRANSACTION(API) in Staking a amount and voting to a delegate

### ISSUE THREAD

**Issue by bbmarley** [AraiEzzra/DDKCORE#805]
I'm Using DDKoin Testnet Here:

In API's of voting for a delegate and staking money asset parameters of "createdAt" is not working (Mainly at Epoch Time)

![stake and voting parameter data](https://user-images.githubusercontent.com/43064317/74130078-3f609e00-4c07-11ea-9f99-f1a6e183d29b.JPG)

I tried methods for epoch time at (createdAt parameter) in NodeJS as shown in the below but the APIs are not working!

epoch time in milliseconds - Date.now()
epoch time not in milliseconds - Math.floor(new Date().getTime()/1000.0)
epoch time - (Math.floor(new Date().getTime()/1000.0)-1451667600)

below is the screenshot I got the error:
![staking ddk](https://user-images.githubusercontent.com/43064317/74130418-0f65ca80-4c08-11ea-932a-67399413bbd1.JPG)

**Comment by axelsheva** [comment]
You must specify `createdAt` in epoch time format. You can use `getTime` method in our `slotService` for it https://github.com/AraiEzzra/DDK.REGISTRY/blob/7ccf0534fc5ea4fab8e3323b5f399ffa2b273b00/src/service/slot.ts

https://github.com/AraiEzzra/DDK.REST.API.CLIENT/blob/master/docs/common/epochtime.md
