### ISSUE TITLE
The issue at CREATE_TRANSACTION(API) SEND DDK 

### ISSUE THREAD

**Issue by vinoddhakad1992** [AraiEzzra/DDKCORE#807]
Hi Team,
I got an error for send coin  "Transaction creation on core is disabled"
I used below Mainnet trusted nodes
68.183.176.187:7008
159.65.131.165:7008
68.183.235.184:7008
157.230.46.24:70008
when we using for send DDK below the code 

{
   "code":"CREATE_TRANSACTION",
   "headers":{
      "id":"f66dbdf3-2860-453d-a535-c1ee8415eb71",
      "type":1
   },
   "body":{
      "secret":"empty hand absent pepper reward music top foil violin disease target exhibit",
      "trs":{
         "senderPublicKey":"f4ae589b02f97e9ab5bce61cf187bcc96cfb3fdf9a11333703a682b7d47c8dc2",
         "type":10,
         "asset":{
            "amount":100000000,
            "recipientAddress":"13917551777668161189"
         }
      }
   }
}

**Comment by furqansiddiqui** [comment]
Share your configuration file

**Comment by axelsheva** [comment]
Hello. Transaction creation on Core is disabled because send your passphrase to our nodes is not secure. Please, use DDK Rest API for it.

**Comment by vinoddhakad1992** [comment]
So please provide me the rest API document and API URL  so that we can implement the api

**Comment by furqansiddiqui** [comment]
All the documentation right now are in this github repository > https://github.com/AraiEzzra/DDK.REST.API.CLIENT
